"""
VeriSpec Continuous Reporter — pytest Plugin (conftest.py)

This file is auto-generated by `verispec init` or `verispec implement`.
It hooks into pytest's execution lifecycle and continuously streams
test results into .verispec/reports/latest/ in three formats:
  - results.json  (machine-readable, live-updated)
  - report.md     (human-readable Markdown)
  - report.html   (interactive visual dashboard)

The HTML dashboard auto-refreshes every 3 seconds, so you can watch
test results appear in real-time by opening report.html in a browser.

USAGE:
  This file should be placed in your tests/ directory (or project root).
  pytest auto-discovers conftest.py files. No additional configuration needed.

  Just run:
    pytest
  
  And reports are generated automatically.

TRACEABILITY:
  Tests decorated with @pytest.mark.verispec() are recognized:
  
    @pytest.mark.verispec(id="TC-JC-001", req="REQ-JC-001", tier="api", priority="P0")
    def test_create_job_card():
        ...

  Tests without the marker are still tracked but without traceability linkage.
"""

import pytest
import json
import os
import re
import shutil
import time
from datetime import datetime, timezone
from pathlib import Path

# ─── Configuration ─────────────────────────────────────────────────────────────

VERISPEC_DIR = Path(".verispec")
REPORTS_DIR = VERISPEC_DIR / "reports"
LATEST_DIR = REPORTS_DIR / "latest"
RESULTS_FILE = LATEST_DIR / "results.json"
REPORT_MD_FILE = LATEST_DIR / "report.md"
REPORT_HTML_FILE = LATEST_DIR / "report.html"
TEMPLATES_DIR = VERISPEC_DIR / "templates"


# ─── VeriSpec Data Store ───────────────────────────────────────────────────────

class VeriSpecStore:
    """Holds all test execution data and writes it to disk continuously."""

    def __init__(self):
        self.run_id = f"RUN-{datetime.now().strftime('%Y%m%d')}-{int(time.time()) % 1000:03d}"
        self.timestamp_start = datetime.now(timezone.utc).isoformat()
        self.timestamp_end = None
        self.status = "running"
        self.tests = []
        self.summary = {
            "total": 0,
            "passed": 0,
            "failed": 0,
            "skipped": 0,
            "errors": 0,
            "pass_rate": 0.0,
            "duration_ms": 0,
        }
        self.tiers = {}
        self.requirements = {}
        self.quality_gates = []

    def add_test(self, test_data):
        """Add a test result and update all aggregations."""
        self.tests.append(test_data)
        self._update_summary()
        self._update_tiers(test_data)
        self._update_requirements(test_data)
        self.flush()

    def finalize(self):
        """Mark the run as complete and compute final quality gates."""
        self.timestamp_end = datetime.now(timezone.utc).isoformat()
        self.status = "passed" if self.summary["failed"] == 0 and self.summary["errors"] == 0 else "failed"
        self._compute_quality_gates()
        self.flush()
        self._archive_run()

    def _update_summary(self):
        total = len(self.tests)
        passed = sum(1 for t in self.tests if t["status"] == "passed")
        failed = sum(1 for t in self.tests if t["status"] == "failed")
        skipped = sum(1 for t in self.tests if t["status"] == "skipped")
        errors = sum(1 for t in self.tests if t["status"] == "error")
        duration = sum(t.get("duration_ms", 0) for t in self.tests)

        self.summary = {
            "total": total,
            "passed": passed,
            "failed": failed,
            "skipped": skipped,
            "errors": errors,
            "pass_rate": round((passed / total * 100), 1) if total > 0 else 0.0,
            "duration_ms": round(duration, 1),
        }

    def _update_tiers(self, test_data):
        tier = test_data.get("tier", "unknown")
        if tier not in self.tiers:
            self.tiers[tier] = {
                "total": 0, "passed": 0, "failed": 0,
                "skipped": 0, "duration_ms": 0, "framework": "pytest"
            }
        t = self.tiers[tier]
        t["total"] += 1
        t[test_data["status"]] = t.get(test_data["status"], 0) + 1
        t["duration_ms"] += test_data.get("duration_ms", 0)

    def _update_requirements(self, test_data):
        req_id = test_data.get("req_id")
        if not req_id:
            return
        # Handle comma-separated requirement IDs
        req_ids = [r.strip() for r in req_id.split(",")]
        for rid in req_ids:
            if rid not in self.requirements:
                self.requirements[rid] = {
                    "req_id": rid,
                    "description": "",
                    "total_tests": 0,
                    "passed": 0,
                    "failed": 0,
                    "status": "untested",
                }
            r = self.requirements[rid]
            r["total_tests"] += 1
            if test_data["status"] == "passed":
                r["passed"] += 1
            elif test_data["status"] in ("failed", "error"):
                r["failed"] += 1
            # Update status
            if r["failed"] > 0:
                r["status"] = "unverified"
            elif r["passed"] == r["total_tests"]:
                r["status"] = "verified"
            else:
                r["status"] = "partial"

    def _compute_quality_gates(self):
        s = self.summary
        total_reqs = len(self.requirements)
        covered_reqs = sum(1 for r in self.requirements.values() if r["total_tests"] > 0)
        verified_reqs = sum(1 for r in self.requirements.values() if r["status"] == "verified")

        self.quality_gates = [
            {
                "name": "Overall Pass Rate",
                "threshold": "≥ 95%",
                "actual": f"{s['pass_rate']}%",
                "passed": s["pass_rate"] >= 95,
            },
            {
                "name": "Zero Critical Failures",
                "threshold": "0 failures",
                "actual": f"{s['failed']} failures",
                "passed": s["failed"] == 0,
            },
            {
                "name": "Requirement Coverage",
                "threshold": "100%",
                "actual": f"{round(covered_reqs/total_reqs*100, 1) if total_reqs > 0 else 0}% ({covered_reqs}/{total_reqs})",
                "passed": covered_reqs == total_reqs if total_reqs > 0 else True,
            },
            {
                "name": "Requirements Verified",
                "threshold": "100%",
                "actual": f"{round(verified_reqs/total_reqs*100, 1) if total_reqs > 0 else 0}% ({verified_reqs}/{total_reqs})",
                "passed": verified_reqs == total_reqs if total_reqs > 0 else True,
            },
        ]

    def flush(self):
        """Write current state to results.json, report.md, and ensure report.html exists."""
        LATEST_DIR.mkdir(parents=True, exist_ok=True)

        # Write results.json
        data = {
            "verispec_version": "0.1.0",
            "run_id": self.run_id,
            "timestamp_start": self.timestamp_start,
            "timestamp_end": self.timestamp_end,
            "status": self.status,
            "execution_mode": "full",
            "summary": self.summary,
            "tiers": self.tiers,
            "requirements": self.requirements,
            "tests": self.tests,
            "quality_gates": self.quality_gates,
            "defects": [],
        }
        with open(RESULTS_FILE, "w") as f:
            json.dump(data, f, indent=2, default=str)

        # Write report.md
        self._write_markdown_report(data)

        # Hydrate report.html with embedded test results
        self._write_html_report(data)

    def _write_html_report(self, data):
        """Write report.html with embedded test results so it opens cleanly via file:// without CORS issues."""
        template_html = TEMPLATES_DIR / "report.template.html"
        source_html = template_html if template_html.exists() else (REPORT_HTML_FILE if REPORT_HTML_FILE.exists() else None)
        if not source_html or not source_html.exists():
            return

        try:
            content = source_html.read_text(encoding="utf-8")
            data_json = json.dumps(data, indent=2, default=str)
            script_tag = f'<script id="verispec-data">window.__VERISPEC_DATA__ = {data_json};</script>'

            if '<script id="verispec-data">' in content:
                content = re.sub(
                    r'<script id="verispec-data">[\s\S]*?</script>',
                    script_tag,
                    content
                )
            elif '</head>' in content:
                content = content.replace('</head>', f'  {script_tag}\n</head>')
            elif '<body>' in content:
                content = content.replace('<body>', f'<body>\n  {script_tag}')
            else:
                content = script_tag + '\n' + content

            REPORT_HTML_FILE.write_text(content, encoding="utf-8")
        except Exception:
            pass

    def _write_markdown_report(self, data):
        s = data["summary"]
        status_icon = "✓" if s["failed"] == 0 else "✗"
        status_text = "ALL PASSED" if s["failed"] == 0 else f"FAILURES DETECTED ({s['failed']})"

        lines = [
            f"# VeriSpec Test Execution Report",
            f"",
            f"> **Run ID**: `{data['run_id']}`",
            f"> **Execution Date**: {data['timestamp_start']}",
            f"> **Overall Status**: {status_icon} **{status_text}**",
            f"",
            f"---",
            f"",
            f"## Executive Summary",
            f"",
            f"| Metric | Value |",
            f"|:---|:---:|",
            f"| **Total Tests** | {s['total']} |",
            f"| **Passed** | {s['passed']} |",
            f"| **Failed** | {s['failed']} |",
            f"| **Skipped** | {s['skipped']} |",
            f"| **Errors** | {s.get('errors', 0)} |",
            f"| **Pass Rate** | **{s['pass_rate']}%** |",
            f"| **Duration** | {s['duration_ms']:.0f}ms |",
            f"",
        ]

        # Requirement status
        if data["requirements"]:
            lines.extend([
                f"---",
                f"",
                f"## Requirement Verification Status",
                f"",
                f"| Requirement ID | Tests | Passed | Failed | Status |",
                f"|---|:---:|:---:|:---:|---|",
            ])
            for rid, req in data["requirements"].items():
                status_str = "🟢 VERIFIED" if req["status"] == "verified" else "🔴 UNVERIFIED" if req["status"] == "unverified" else "🟡 PARTIAL"
                lines.append(f"| `{req['req_id']}` | {req['total_tests']} | {req['passed']} | {req['failed']} | {status_str} |")
            lines.append("")

        # Tier breakdown
        if data["tiers"]:
            lines.extend([
                f"---",
                f"",
                f"## Test Tier Breakdown",
                f"",
                f"| Tier | Total | Passed | Failed | Skipped | Pass Rate |",
                f"|---|:---:|:---:|:---:|:---:|:---:|",
            ])
            for name, tier in data["tiers"].items():
                tier_rate = round(tier["passed"] / tier["total"] * 100, 1) if tier["total"] > 0 else 0
                lines.append(f"| **{name}** | {tier['total']} | {tier['passed']} | {tier['failed']} | {tier['skipped']} | {tier_rate}% |")
            lines.append("")

        # Failed tests
        failed = [t for t in data["tests"] if t["status"] in ("failed", "error")]
        if failed:
            lines.extend([
                f"---",
                f"",
                f"## Failed Tests",
                f"",
            ])
            for t in failed:
                lines.extend([
                    f"### ✗ {t.get('name', t.get('function', 'Unknown'))}",
                    f"- **Test Case**: `{t.get('tc_id', '—')}`",
                    f"- **Requirement**: `{t.get('req_id', '—')}`",
                    f"- **Tier**: {t.get('tier', '—')}",
                    f"- **File**: `{t.get('file', '—')}`",
                    f"- **Error**:",
                    f"```",
                    f"{t.get('error_message', 'No error message captured')}",
                    f"```",
                    f"",
                ])

        # Quality gates
        if data["quality_gates"]:
            lines.extend([
                f"---",
                f"",
                f"## Quality Gates",
                f"",
                f"| Gate | Threshold | Actual | Status |",
                f"|---|---|---|---|",
            ])
            for g in data["quality_gates"]:
                icon = "✓" if g["passed"] else "✗"
                lines.append(f"| {g['name']} | {g['threshold']} | {g['actual']} | {icon} |")
            lines.append("")

        lines.extend([
            f"---",
            f"",
            f"*Continuously generated by VeriSpec Reporter*",
        ])

        with open(REPORT_MD_FILE, "w") as f:
            f.write("\n".join(lines))

    def _archive_run(self):
        """Archive the current run to a timestamped directory."""
        archive_dir = REPORTS_DIR / self.run_id
        if archive_dir.exists():
            return
        try:
            shutil.copytree(LATEST_DIR, archive_dir)
        except Exception:
            pass  # Silently skip archive failures


# ─── Pytest Hooks ──────────────────────────────────────────────────────────────

# Global store instance
_store = None


def _extract_verispec_marker(item):
    """Extract VeriSpec marker data from a test item."""
    marker = item.get_closest_marker("verispec")
    if marker:
        return {
            "tc_id": marker.kwargs.get("id", ""),
            "req_id": marker.kwargs.get("req", ""),
            "tier": marker.kwargs.get("tier", "unknown"),
            "priority": marker.kwargs.get("priority", ""),
        }
    
    # Fallback: try to detect tier from path
    nodeid = item.nodeid
    tier = "unknown"
    if "/unit/" in nodeid or "\\unit\\" in nodeid:
        tier = "unit"
    elif "/api/" in nodeid or "\\api\\" in nodeid:
        tier = "api"
    elif "/integration/" in nodeid or "\\integration\\" in nodeid:
        tier = "integration"
    elif "/e2e/" in nodeid or "\\e2e\\" in nodeid:
        tier = "e2e"
    elif "/security/" in nodeid or "\\security\\" in nodeid:
        tier = "security"
    elif "/perf/" in nodeid or "/performance/" in nodeid:
        tier = "performance"

    return {
        "tc_id": "",
        "req_id": "",
        "tier": tier,
        "priority": "",
    }


def pytest_configure(config):
    """Register the verispec marker and initialize the store."""
    config.addinivalue_line(
        "markers",
        "verispec(id, req, tier, priority): Mark a test with VeriSpec traceability data"
    )


def pytest_sessionstart(session):
    """Initialize VeriSpec store at the start of a test session."""
    global _store
    if VERISPEC_DIR.exists():
        _store = VeriSpecStore()
    else:
        _store = None


def pytest_runtest_logreport(report):
    """Called after each test phase (setup, call, teardown)."""
    global _store
    if _store is None:
        return

    # Only process the 'call' phase (actual test execution)
    if report.when != "call":
        return

    item = report

    # Extract marker data
    # We need the item, not the report — use the node
    marker_data = {"tc_id": "", "req_id": "", "tier": "unknown", "priority": ""}

    # Try to get marker from nodeid path
    nodeid = report.nodeid
    tier = "unknown"
    if "/unit/" in nodeid or "\\unit\\" in nodeid:
        tier = "unit"
    elif "/api/" in nodeid or "\\api\\" in nodeid:
        tier = "api"
    elif "/integration/" in nodeid or "\\integration\\" in nodeid:
        tier = "integration"
    elif "/e2e/" in nodeid or "\\e2e\\" in nodeid:
        tier = "e2e"
    elif "/security/" in nodeid or "\\security\\" in nodeid:
        tier = "security"
    elif "/perf/" in nodeid or "/performance/" in nodeid:
        tier = "performance"

    # Extract VeriSpec metadata from test properties
    tc_id = ""
    req_id = ""
    priority = ""

    for prop_name, prop_value in report.user_properties:
        if prop_name == "verispec_id":
            tc_id = prop_value
        elif prop_name == "verispec_req":
            req_id = prop_value
        elif prop_name == "verispec_tier":
            tier = prop_value
        elif prop_name == "verispec_priority":
            priority = prop_value

    # Map status
    status = "passed" if report.passed else "failed" if report.failed else "skipped"

    # Extract error info
    error_message = None
    stack_trace = None
    if report.failed:
        error_message = str(report.longrepr) if report.longrepr else "Unknown failure"
        if hasattr(report.longrepr, 'reprtraceback'):
            stack_trace = str(report.longrepr.reprtraceback)

    # Build test result entry
    test_data = {
        "tc_id": tc_id,
        "req_id": req_id,
        "name": nodeid.split("::")[-1] if "::" in nodeid else nodeid,
        "file": nodeid.split("::")[0] if "::" in nodeid else "",
        "function": nodeid.split("::")[-1] if "::" in nodeid else nodeid,
        "tier": tier,
        "priority": priority,
        "status": status,
        "duration_ms": round(report.duration * 1000, 1),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "error_message": error_message,
        "stack_trace": stack_trace,
        "stdout": report.capstdout if hasattr(report, 'capstdout') else None,
        "stderr": report.capstderr if hasattr(report, 'capstderr') else None,
    }

    _store.add_test(test_data)


def pytest_runtest_setup(item):
    """Extract VeriSpec marker data and add as user properties for the reporter."""
    marker = item.get_closest_marker("verispec")
    if marker:
        item.user_properties.append(("verispec_id", marker.kwargs.get("id", "")))
        item.user_properties.append(("verispec_req", marker.kwargs.get("req", "")))
        item.user_properties.append(("verispec_tier", marker.kwargs.get("tier", "unknown")))
        item.user_properties.append(("verispec_priority", marker.kwargs.get("priority", "")))


def pytest_sessionfinish(session, exitstatus):
    """Finalize VeriSpec report at the end of the session."""
    global _store
    if _store is not None:
        _store.finalize()


def pytest_collection_modifyitems(config, items):
    """Log the number of collected tests."""
    global _store
    if _store is None:
        return
    # We could update expected total here if needed
