/**
 * VeriSpec Continuous Reporter — Playwright
 * 
 * This reporter hooks into Playwright's test execution lifecycle
 * and continuously streams results into .verispec/reports/latest/.
 * 
 * Auto-generated by `verispec init` or `verispec implement`.
 * 
 * USAGE:
 *   Add to playwright.config.ts:
 * 
 *   export default defineConfig({
 *     reporter: [
 *       ['list'],
 *       ['./.verispec/reporters/verispec-playwright-reporter.ts'],
 *     ],
 *   });
 * 
 * TRACEABILITY:
 *   Use test.info().annotations to add VeriSpec metadata:
 * 
 *   test('create job card', async ({ page }) => {
 *     test.info().annotations.push(
 *       { type: 'verispec_id', description: 'TC-JC-001' },
 *       { type: 'verispec_req', description: 'REQ-JC-001' },
 *       { type: 'verispec_tier', description: 'e2e' },
 *       { type: 'verispec_priority', description: 'P0' },
 *     );
 *     // ... test code
 *   });
 */

import fs from 'fs';
import path from 'path';
import type {
  FullConfig,
  FullResult,
  Reporter,
  Suite,
  TestCase,
  TestResult,
} from '@playwright/test/reporter';

const VERISPEC_DIR = '.verispec';
const REPORTS_DIR = path.join(VERISPEC_DIR, 'reports');
const LATEST_DIR = path.join(REPORTS_DIR, 'latest');
const RESULTS_FILE = path.join(LATEST_DIR, 'results.json');
const REPORT_MD_FILE = path.join(LATEST_DIR, 'report.md');
const REPORT_HTML_FILE = path.join(LATEST_DIR, 'report.html');
const TEMPLATES_DIR = path.join(VERISPEC_DIR, 'templates');

interface VeriSpecTestEntry {
  tc_id: string;
  req_id: string;
  name: string;
  file: string;
  function: string;
  tier: string;
  priority: string;
  status: 'passed' | 'failed' | 'skipped' | 'error';
  duration_ms: number;
  timestamp: string;
  error_message: string | null;
  stack_trace: string | null;
  stdout: string | null;
  stderr: string | null;
}

interface VeriSpecResults {
  verispec_version: string;
  run_id: string;
  timestamp_start: string;
  timestamp_end: string | null;
  status: 'running' | 'passed' | 'failed' | 'error';
  execution_mode: string;
  summary: {
    total: number;
    passed: number;
    failed: number;
    skipped: number;
    errors: number;
    pass_rate: number;
    duration_ms: number;
  };
  tiers: Record<string, { total: number; passed: number; failed: number; skipped: number; duration_ms: number; framework: string }>;
  requirements: Record<string, { req_id: string; description: string; total_tests: number; passed: number; failed: number; status: string }>;
  tests: VeriSpecTestEntry[];
  quality_gates: Array<{ name: string; threshold: string; actual: string; passed: boolean }>;
  defects: unknown[];
}

class VeriSpecPlaywrightReporter implements Reporter {
  private results: VeriSpecResults;

  constructor() {
    const now = new Date();
    const dateStr = now.toISOString().slice(0, 10).replace(/-/g, '');
    const seq = (now.getTime() % 1000).toString().padStart(3, '0');

    this.results = {
      verispec_version: '0.1.0',
      run_id: `RUN-${dateStr}-${seq}`,
      timestamp_start: now.toISOString(),
      timestamp_end: null,
      status: 'running',
      execution_mode: 'full',
      summary: { total: 0, passed: 0, failed: 0, skipped: 0, errors: 0, pass_rate: 0, duration_ms: 0 },
      tiers: {},
      requirements: {},
      tests: [],
      quality_gates: [],
      defects: [],
    };
  }

  onBegin(_config: FullConfig, _suite: Suite): void {
    // Ensure output directory exists
    fs.mkdirSync(LATEST_DIR, { recursive: true });

    // Copy HTML template if not present
    if (!fs.existsSync(REPORT_HTML_FILE)) {
      const templateHtml = path.join(TEMPLATES_DIR, 'report.template.html');
      if (fs.existsSync(templateHtml)) {
        fs.copyFileSync(templateHtml, REPORT_HTML_FILE);
      }
    }

    this.flush();
  }

  onTestEnd(test: TestCase, result: TestResult): void {
    // Extract VeriSpec annotations
    let tcId = '';
    let reqId = '';
    let tier = 'e2e';
    let priority = '';

    for (const annotation of test.annotations) {
      switch (annotation.type) {
        case 'verispec_id': tcId = annotation.description || ''; break;
        case 'verispec_req': reqId = annotation.description || ''; break;
        case 'verispec_tier': tier = annotation.description || 'e2e'; break;
        case 'verispec_priority': priority = annotation.description || ''; break;
      }
    }

    // Detect tier from file path if not annotated
    const filePath = test.location?.file || '';
    if (tier === 'e2e' && filePath) {
      if (filePath.includes('/unit/') || filePath.includes('\\unit\\')) tier = 'unit';
      else if (filePath.includes('/api/') || filePath.includes('\\api\\')) tier = 'api';
      else if (filePath.includes('/integration/') || filePath.includes('\\integration\\')) tier = 'integration';
      else if (filePath.includes('/security/') || filePath.includes('\\security\\')) tier = 'security';
    }

    // Map status
    let status: VeriSpecTestEntry['status'] = 'passed';
    if (result.status === 'failed' || result.status === 'timedOut') status = 'failed';
    else if (result.status === 'skipped') status = 'skipped';
    else if (result.status === 'interrupted') status = 'error';

    // Extract error info
    let errorMessage: string | null = null;
    let stackTrace: string | null = null;
    if (result.errors && result.errors.length > 0) {
      errorMessage = result.errors.map(e => e.message || '').join('\n');
      stackTrace = result.errors.map(e => e.stack || '').join('\n');
    }

    const entry: VeriSpecTestEntry = {
      tc_id: tcId,
      req_id: reqId,
      name: test.title,
      file: filePath,
      function: test.title,
      tier,
      priority,
      status,
      duration_ms: result.duration,
      timestamp: new Date().toISOString(),
      error_message: errorMessage,
      stack_trace: stackTrace,
      stdout: result.stdout?.map(s => s.text || '').join('') || null,
      stderr: result.stderr?.map(s => s.text || '').join('') || null,
    };

    this.results.tests.push(entry);
    this.updateSummary();
    this.updateTier(entry);
    this.updateRequirements(entry);
    this.flush();
  }

  onEnd(result: FullResult): void {
    this.results.timestamp_end = new Date().toISOString();
    this.results.status = this.results.summary.failed === 0 && this.results.summary.errors === 0 ? 'passed' : 'failed';
    this.computeQualityGates();
    this.flush();
    this.archiveRun();
  }

  private updateSummary(): void {
    const tests = this.results.tests;
    const total = tests.length;
    const passed = tests.filter(t => t.status === 'passed').length;
    const failed = tests.filter(t => t.status === 'failed').length;
    const skipped = tests.filter(t => t.status === 'skipped').length;
    const errors = tests.filter(t => t.status === 'error').length;
    const duration = tests.reduce((sum, t) => sum + (t.duration_ms || 0), 0);

    this.results.summary = {
      total, passed, failed, skipped, errors,
      pass_rate: total > 0 ? Math.round((passed / total) * 1000) / 10 : 0,
      duration_ms: Math.round(duration * 10) / 10,
    };
  }

  private updateTier(entry: VeriSpecTestEntry): void {
    const tier = entry.tier;
    if (!this.results.tiers[tier]) {
      this.results.tiers[tier] = { total: 0, passed: 0, failed: 0, skipped: 0, duration_ms: 0, framework: 'playwright' };
    }
    const t = this.results.tiers[tier];
    t.total++;
    (t as Record<string, number>)[entry.status] = ((t as Record<string, number>)[entry.status] || 0) + 1;
    t.duration_ms += entry.duration_ms || 0;
  }

  private updateRequirements(entry: VeriSpecTestEntry): void {
    if (!entry.req_id) return;
    const reqIds = entry.req_id.split(',').map(r => r.trim());
    for (const rid of reqIds) {
      if (!this.results.requirements[rid]) {
        this.results.requirements[rid] = { req_id: rid, description: '', total_tests: 0, passed: 0, failed: 0, status: 'untested' };
      }
      const r = this.results.requirements[rid];
      r.total_tests++;
      if (entry.status === 'passed') r.passed++;
      else if (entry.status === 'failed' || entry.status === 'error') r.failed++;
      r.status = r.failed > 0 ? 'unverified' : r.passed === r.total_tests ? 'verified' : 'partial';
    }
  }

  private computeQualityGates(): void {
    const s = this.results.summary;
    const totalReqs = Object.keys(this.results.requirements).length;
    const coveredReqs = Object.values(this.results.requirements).filter(r => r.total_tests > 0).length;
    const verifiedReqs = Object.values(this.results.requirements).filter(r => r.status === 'verified').length;

    this.results.quality_gates = [
      { name: 'Overall Pass Rate', threshold: '≥ 95%', actual: `${s.pass_rate}%`, passed: s.pass_rate >= 95 },
      { name: 'Zero Critical Failures', threshold: '0 failures', actual: `${s.failed} failures`, passed: s.failed === 0 },
      { name: 'Requirement Coverage', threshold: '100%', actual: totalReqs > 0 ? `${Math.round(coveredReqs / totalReqs * 1000) / 10}%` : 'N/A', passed: totalReqs === 0 || coveredReqs === totalReqs },
      { name: 'Requirements Verified', threshold: '100%', actual: totalReqs > 0 ? `${Math.round(verifiedReqs / totalReqs * 1000) / 10}%` : 'N/A', passed: totalReqs === 0 || verifiedReqs === totalReqs },
    ];
  }

  private flush(): void {
    try {
      fs.mkdirSync(LATEST_DIR, { recursive: true });
      fs.writeFileSync(RESULTS_FILE, JSON.stringify(this.results, null, 2));
      this.writeMarkdownReport();
      this.writeHtmlReport();
    } catch (e) {
      // Silently handle write errors
    }
  }

  private writeHtmlReport(): void {
    const templatePath = path.join(TEMPLATES_DIR, 'report.template.html');
    const sourcePath = fs.existsSync(templatePath) ? templatePath : (fs.existsSync(REPORT_HTML_FILE) ? REPORT_HTML_FILE : null);
    if (!sourcePath) return;

    try {
      let content = fs.readFileSync(sourcePath, 'utf-8');
      const scriptTag = `<script id="verispec-data">window.__VERISPEC_DATA__ = ${JSON.stringify(this.results, null, 2)};</script>`;
      if (content.includes('<script id="verispec-data">')) {
        content = content.replace(/<script id="verispec-data">[\s\S]*?<\/script>/, scriptTag);
      } else if (content.includes('</head>')) {
        content = content.replace('</head>', `  ${scriptTag}\n</head>`);
      } else if (content.includes('<body>')) {
        content = content.replace('<body>', `<body>\n  ${scriptTag}`);
      } else {
        content = scriptTag + '\n' + content;
      }
      fs.writeFileSync(REPORT_HTML_FILE, content, 'utf-8');
    } catch (e) {
      // Silently handle write errors
    }
  }

  private writeMarkdownReport(): void {
    const s = this.results.summary;
    const statusIcon = s.failed === 0 ? '✓' : '✗';
    const statusText = s.failed === 0 ? 'ALL PASSED' : `FAILURES DETECTED (${s.failed})`;

    let md = `# VeriSpec Test Execution Report\n\n`;
    md += `> **Run ID**: \`${this.results.run_id}\`\n`;
    md += `> **Execution Date**: ${this.results.timestamp_start}\n`;
    md += `> **Overall Status**: ${statusIcon} **${statusText}**\n\n---\n\n`;
    md += `## Executive Summary\n\n`;
    md += `| Metric | Value |\n|:---|:---:|\n`;
    md += `| **Total Tests** | ${s.total} |\n`;
    md += `| **Passed** | ${s.passed} |\n`;
    md += `| **Failed** | ${s.failed} |\n`;
    md += `| **Pass Rate** | **${s.pass_rate}%** |\n`;
    md += `| **Duration** | ${Math.round(s.duration_ms)}ms |\n\n`;

    if (Object.keys(this.results.requirements).length > 0) {
      md += `---\n\n## Requirement Verification\n\n`;
      md += `| Requirement | Tests | Passed | Failed | Status |\n|---|:---:|:---:|:---:|---|\n`;
      for (const req of Object.values(this.results.requirements)) {
        const st = req.status === 'verified' ? '🟢 VERIFIED' : req.status === 'unverified' ? '🔴 UNVERIFIED' : '🟡 PARTIAL';
        md += `| \`${req.req_id}\` | ${req.total_tests} | ${req.passed} | ${req.failed} | ${st} |\n`;
      }
      md += '\n';
    }

    const failed = this.results.tests.filter(t => t.status === 'failed' || t.status === 'error');
    if (failed.length > 0) {
      md += `---\n\n## Failed Tests\n\n`;
      for (const t of failed) {
        md += `### ✗ ${t.name}\n`;
        md += `- **Test Case**: \`${t.tc_id || '—'}\`\n`;
        md += `- **Requirement**: \`${t.req_id || '—'}\`\n`;
        md += `- **File**: \`${t.file || '—'}\`\n`;
        if (t.error_message) md += `- **Error**:\n\`\`\`\n${t.error_message}\n\`\`\`\n\n`;
      }
    }

    md += `---\n\n*Continuously generated by VeriSpec Playwright Reporter*\n`;

    try {
      fs.writeFileSync(REPORT_MD_FILE, md);
    } catch (e) { /* ignore */ }
  }

  private archiveRun(): void {
    const archiveDir = path.join(REPORTS_DIR, this.results.run_id);
    if (fs.existsSync(archiveDir)) return;
    try {
      fs.cpSync(LATEST_DIR, archiveDir, { recursive: true });
    } catch (e) { /* ignore */ }
  }
}

export default VeriSpecPlaywrightReporter;
